name: .NET Core CI with Litters

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      continue-on-error: true
      with:
        dotnet-version: '8.x'
        dotnet-quality: 'ga'

    - name: Install Litters
      run: dotnet tool install --global StyleCop.Analyzers

    - name: Run Litters
      run: |
        dotnet tool run StyleCop.Analyzers

    - name: Build with dotnet
      run: dotnet build

    - name: Run tests
      run: dotnet test
